version: '3.4'

services:
  shoplanddb:
    container_name: shoplanddb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ShopLandDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5070:80"

  shopland.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10000:8080"