version: '3.4'

services:
  shoplanddb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  shopland.api:
    image: ${DOCKER_REGISTRY-}shoplandapi
    build:
      context: .
      dockerfile: ShopLand.Api/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
