// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopLand.Infrastructure.Persistance.Context;

#nullable disable

namespace ShopLand.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240301081419_AccountMig")]
    partial class AccountMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopLand.Domain.Account.Roles.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acf9cfc1-b18c-4e03-8b34-2207c8b2347b"),
                            Name = "Customer"
                        },
                        new
                        {
                            Id = new Guid("565a390b-2e0f-4af1-a0a6-7cc6d512a1a2"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ShopLand.Domain.Account.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("FullName");

                    b.Property<string>("_password")
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopLand.Domain.Account.Users.ValueObject.UserInRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserInRoles");
                });

            modelBuilder.Entity("ShopLand.Domain.Account.Users.ValueObject.UserInRole", b =>
                {
                    b.HasOne("ShopLand.Domain.Account.Users.Entities.User", null)
                        .WithMany("_usedInRoles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ShopLand.Domain.Account.Users.Entities.User", b =>
                {
                    b.Navigation("_usedInRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
